[13/Dec/2020 14:16:27 django.request-ERROR]: Internal Server Error: /admin/customer/customer/
Traceback (most recent call last):
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 79, in execute
    return self.cursor.execute(query, args)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'customer_customer.shorted_access_token' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1811, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/debug_toolbar/panels/sql/tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/debug_toolbar/panels/sql/tracking.py", line 133, in _record
    return method(sql, params)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 79, in execute
    return self.cursor.execute(query, args)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/tringuyen/PycharmProjects/facebookApp/center/lib/python3.9/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.OperationalError: (1054, "Unknown column 'customer_customer.shorted_access_token' in 'field list'")
[13/Dec/2020 14:16:27 django.server-ERROR]: "GET /admin/customer/customer/ HTTP/1.1" 500 247017
[13/Dec/2020 14:18:12 get_api-WARNING]: METHOD=GET
STATUS=400
CLASS=BaseRequest
URL=https://graph.facebook.com/v9.0/oauth/access_token?client_id=2586040028170400&redirect_uri=https%3A%2F%2F7761587b7857.ngrok.io%2F&client_secret=fbdf2f3366974aca738d782e1be4a259&code=AQBUH8f4UQVT7bQ6Wp_UDHac6bNVt0kXsOvC5Q4eiCURNFi9SkjeHuXJYtsznBTFSl-zJ-1v59tvFYvx0a5s5rFbwsV3G0iVOwe-zwGpg9OmX0BPxaHUhblRHFzMgOohQ-OfwE0FvQ0jx_z30n8_NyFrVpaXtZK__lds4Q_sPXFNdWpFphmvk8NYfRSFsx1Au-uq_3Ht_GXDZ9SUKSnMo03PDCu6B13XtlhGIZfBoGEy-m4dsnXDtc2gVQh3Y7JvO-bu3PNJOSmXaA1s_ujaws4AFNtgdIP4NWrrHAZFmJ0f-KWQP1UVD3txDoN5f4nK6hR7F0GCkDD_BwoxU5DDVDft 
RESPONSE={"error": {"message": "This authorization code has been used.", "type": "OAuthException", "code": 100, "error_subcode": 36009, "fbtrace_id": "Aw-Gmmoh9i5GKXSQXsmwJCa"}}

[13/Dec/2020 14:18:12 get_api-WARNING]: METHOD=GET
STATUS=400
CLASS=BaseRequest
URL=https://graph.facebook.com/v9.0/oauth/access_token?client_id=2586040028170400&redirect_uri=https%3A%2F%2F7761587b7857.ngrok.io%2F&client_secret=fbdf2f3366974aca738d782e1be4a259&code=AQBUH8f4UQVT7bQ6Wp_UDHac6bNVt0kXsOvC5Q4eiCURNFi9SkjeHuXJYtsznBTFSl-zJ-1v59tvFYvx0a5s5rFbwsV3G0iVOwe-zwGpg9OmX0BPxaHUhblRHFzMgOohQ-OfwE0FvQ0jx_z30n8_NyFrVpaXtZK__lds4Q_sPXFNdWpFphmvk8NYfRSFsx1Au-uq_3Ht_GXDZ9SUKSnMo03PDCu6B13XtlhGIZfBoGEy-m4dsnXDtc2gVQh3Y7JvO-bu3PNJOSmXaA1s_ujaws4AFNtgdIP4NWrrHAZFmJ0f-KWQP1UVD3txDoN5f4nK6hR7F0GCkDD_BwoxU5DDVDft 
RESPONSE={"error": {"message": "This authorization code has been used.", "type": "OAuthException", "code": 100, "error_subcode": 36009, "fbtrace_id": "Aw-Gmmoh9i5GKXSQXsmwJCa"}}

[13/Dec/2020 14:18:12 get_api-WARNING]: METHOD=GET
STATUS=400
CLASS=Info
URL=https://graph.facebook.com/v9.0/me?fields=email,name,id,first_name,last_name 
RESPONSE={"error": {"message": "An active access token must be used to query information about the current user.", "type": "OAuthException", "code": 2500, "fbtrace_id": "A1jleBAW42OaI0aJRwqHFP4"}}

[13/Dec/2020 14:18:12 get_api-WARNING]: METHOD=GET
STATUS=400
CLASS=Info
URL=https://graph.facebook.com/v9.0/me?fields=email,name,id,first_name,last_name 
RESPONSE={"error": {"message": "An active access token must be used to query information about the current user.", "type": "OAuthException", "code": 2500, "fbtrace_id": "A1jleBAW42OaI0aJRwqHFP4"}}

